# Generated by Django 4.2.3 on 2023-07-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='subtitle',
            field=models.CharField(max_length=200),
        ),
    ]
