# Generated by Django 4.2.3 on 2023-07-25 21:13

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_description_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Overview'),
        ),
    ]
